# HTTP Server
server:
  port: 8888

spring:
  # Spring Cloud Config Server Repository
  cloud:
    config:
      server:
        git:
          uri: https://github.com/victoraa/SpringCloudConfig-GitRepository


  # Spring properties
  profiles:
    active: dev
    
   
#http://localhost:8888/actuator/health   
#http://localhost:8888/application/default